'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { Check, Mail, MapPin, Phone } from 'lucide-react';
import { Logo } from '@/components/Logo';
import { navItems } from '@/lib/tevexxo-data';

export default function ContactPage() {
  const [submitted, setSubmitted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const email = String(form.get('email') || ''); if (!String(form.get('name') || '').trim() || !email.includes('@') || !String(form.get('message') || '').trim()) { setError('Please complete the required fields with valid details.'); return; } setBusy(true); window.setTimeout(() => { setBusy(false); setSubmitted(true); }, 700); };
  return <div className="min-h-screen bg-[#f7f6f2]"><header className="border-b border-slate-200 bg-white"><div className="container-shell flex h-[76px] items-center justify-between gap-6"><Link href="/" aria-label="Tevexxo home"><Logo compact /></Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Primary navigation">{navItems.map(item => <Link key={item.href} href={item.href} className="text-sm text-slate-600 transition hover:text-[#ff5a00]">{item.label}</Link>)}</nav><Link href="/contact" className="rounded-full bg-[#ff5a00] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#ff6e21]">Get started</Link></div></header>
    <section className="container-shell py-20"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#ff5a00]">Contact</p><h1 className="mt-4 max-w-3xl font-display text-5xl font-bold tracking-[-0.04em]">Let&apos;s talk about your next step.</h1><p className="mt-6 max-w-2xl text-lg text-slate-500">Questions about a course, a program, or a partnership? We usually reply within one business day.</p>
      <div className="mt-14 grid gap-10 lg:grid-cols-[1fr_1.1fr]"><div className="grid gap-4"><a href="mailto:hello@tevexxo.com" className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#ff5a00]"><Mail size={20} /></span><div><p className="text-sm text-slate-500">Email</p><p className="font-semibold">hello@tevexxo.com</p></div></a><a href="tel:+910000000000" className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#ff5a00]"><Phone size={20} /></span><div><p className="text-sm text-slate-500">Phone</p><p className="font-semibold">+91 00000 00000</p></div></a><div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#ff5a00]"><MapPin size={20} /></span><div><p className="text-sm text-slate-500">Studio</p><p className="font-semibold">Bengaluru, India</p></div></div></div>
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">{submitted ? <div className="py-16 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-green-700"><Check /></div><h2 className="mt-5 text-2xl font-bold">Message sent.</h2><p className="mt-2 text-slate-500">Thanks for reaching out — we&apos;ll be in touch soon.</p></div> : <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Name *<input name="name" className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5a00]" placeholder="Your name" /></label><label className="grid gap-2 text-sm font-medium">Email *<input name="email" type="email" className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5a00]" placeholder="you@example.com" /></label><label className="grid gap-2 text-sm font-medium">Phone<input name="phone" className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5a00]" placeholder="+91 00000 00000" /></label><label className="grid gap-2 text-sm font-medium">Subject<input name="subject" className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5a00]" placeholder="How can we help?" /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Message *<textarea name="message" rows={4} className="rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#ff5a00]" placeholder="Tell us a little about your goals." /></label>{error && <p className="text-sm text-red-600 sm:col-span-2">{error}</p>}<button disabled={busy} className="rounded-xl bg-[#ff5a00] px-5 py-3 font-semibold text-white transition hover:bg-[#e94f00] disabled:opacity-60 sm:col-span-2">{busy ? 'Sending...' : 'Send message'}</button></form>}</div></div></section></div>;
}
